# 应用服务 WEB 访问端口
server:
  port: 9002

# 应用名称
spring:
  application:
    name: cloudalibaba-provider-payment
  # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# Actuator Web 访问端口
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

