server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
#        nacos服务注册中心地址
        server-addr: localhost:8848
#        关闭sentinel的CommonFilter实例化
    sentinel:
      transport:
#        配置sentinel dashboard地址
        dashboard: localhost:8080
#        默认8719端口，如果该端口被占用，则会依次+1扫描未被占用的端口号
        port: 8719
      datasource:
        ds1: #名称，随意
          nacos:
            server-addr: localhost:8848 #sentinel地址
            dataId: cloudalibaba-sentinel-service #nacos里面配置文件的dataid
            groupId: DEFAULT_GROUP #nacos里面配置文件的groupid
            data-type: json #nacos里面配置文件的类型
            rule-type: flow



management:
  endpoints:
    web:
      exposure:
        include: '*'